apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    name: flask-app-service
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000

  selector:
    name: flask-app-pod
    app: flask-app
    role: frontend
